namespace FB_CRM_Lib.Structs
{
    public struct NationalityResidencyCode
    {
        public static string Afghanistan => "AF";  //Afghanistan 
        public static string Albania => "AL";  //Albania 
        public static string Algeria => "DZ";  //Algeria 
        public static string AmericanSamoa => "AS";  //American Samoa 
        public static string Andorra => "AD";  //Andorra 
        public static string Angola => "AO";  //Angola 
        public static string Anguilla => "AI";  //Anguilla 
        public static string Antartica => "AQ";  //Antartica 
        public static string AntiguaAndBarbuda => "AG";  //Antigua and Barbuda 
        public static string Argentina => "AR";  //Argentina 
        public static string Armenia => "AM";  //Armenia 
        public static string Aruba => "AW";  //Aruba 
        public static string Australia => "AU";  //Australia 
        public static string Austria => "AT";  //Austria 
        public static string Azerbaijan => "AZ";  //Azerbaijan 
        public static string Bahamas => "BS";  //Bahamas 
        public static string Bahrain => "BH";  //Bahrain 
        public static string Bangladesh => "BD";  //Bangladesh 
        public static string Barbados => "BB";  //Barbados 
        public static string Belarus => "BY";  //Belarus 
        public static string Belgium => "BE";  //Belgium 
        public static string Belize => "BZ";  //Belize 
        public static string Benin => "BJ";  //Benin 
        public static string Bermuda => "BM";  //Bermuda 
        public static string Bhutan => "BT";  //Bhutan 
        public static string Bolivia => "BO";  //Bolivia 
        public static string BosniaHerzegovina => "BA";  //Bosnia-Herzegovina 
        public static string Botswana => "BW";  //Botswana 
        public static string BouvetIsland => "BV";  //Bouvet Island 
        public static string Brazil => "BR";  //Brazil 
        public static string BritishIndian => "IO";  //British Indian Oc Te 
        public static string BruneiDarussalam => "BN";  //Brunei Darussalam 
        public static string Bulgaria => "BG";  //Bulgaria 
        public static string BurkinaFasso => "BF";  //Burkina Fasso 
        public static string Burundi => "BI";  //Burundi 
        public static string Cambodia => "KH";  //Cambodia 
        public static string Cameroon => "CM";  //Cameroon 
        public static string Canada => "CA";  //Canada 
        public static string CapeVerde => "CV";  //Cape Verde 
        public static string CaymanIslands => "KY";  //Cayman Islands 
        public static string CentralAfricanRep => "CF";  //Central African Rep 
        public static string Chad => "TD";  //Chad 
        public static string Chile => "CL";  //Chile 
        public static string China => "CN";  //China 
        public static string ChristmasIsland => "CX";  //Christmas Island 
        public static string CocosKeelingIs => "CC";  //Cocos (Keeling) Is 
        public static string Columbia => "CO";  //Columbia 
        public static string Comoros => "KM";  //Comoros 
        public static string Congo => "CG";  //Congo 
        public static string CookIslands => "CK";  //Cook Islands 
        public static string CostaRica => "CR";  //Costa Rica 
        public static string CoteDIvoire => "IC";  //Cote d'Ivoire 
        public static string Croatia => "HR";  //Croatia 
        public static string Cuba => "CU";  //Cuba 
        public static string Cyprus => "CY";  //Cyprus 
        public static string CzechRepublic => "CZ";  //Czech Republic 
        public static string Denmark => "DK";  //Denmark 
        public static string Djibouti => "DJ";  //Djibouti 
        public static string Dominica => "DM";  //Dominica 
        public static string DominicanRepublic => "DO";  //Dominican Republic 
        public static string EastTimor => "TP";  //East Timor 
        public static string Ecuador => "EC";  //Ecuador 
        public static string Egypt => "EG";  //Egypt 
        public static string ElSalvador => "SV";  //El Salvador 
        public static string EquatorialGuinea => "GQ";  //Equatorial Guinea 
        public static string Eritrea => "ER";  //Eritrea 
        public static string Estonia => "EE";  //Estonia 
        public static string Ethiopia => "ET";  //Ethiopia 
        public static string FaeroeIslands => "FO";  //Faeroe Islands 
        public static string FalklandIslands => "FK";  //Falkland Islands 
        public static string Fiji => "FJ";  //Fiji 
        public static string Finland => "FI";  //Finland 
        public static string France => "FR";  //France 
        public static string FrenchGuiana => "GF";  //French Guiana 
        public static string FrenchPolynesia => "PF";  //French Polynesia 
        public static string FrenchSthnTerr  => "TF";  //French S'thn Terr. 
        public static string Gabon => "GA";  //Gabon 
        public static string Gambia => "GM";  //Gambia 
        public static string Georgia => "GE";  //Georgia 
        public static string Germany => "DE";  //Germany 
        public static string Ghana => "GH";  //Ghana 
        public static string Gibraltar => "GI";  //Gibraltar 
        public static string Greece => "GR";  //Greece 
        public static string Greenland => "GL";  //Greenland 
        public static string Grenada => "GD";  //Grenada 
        public static string Guadeloupe => "GP";  //Guadeloupe 
        public static string Guam => "GU";  //Guam 
        public static string Guatemala => "GT";  //Guatemala 
        public static string GuernseyCI => "GG";  //Guernsey C.I. 
        public static string Guinea => "GN";  //Guinea 
        public static string GuineaBissau => "GW";  //Guinea-Bissau 
        public static string Guyana => "GY";  //Guyana 
        public static string Haiti => "HT";  //Haiti 
        public static string HeardAndMcDonaldIs => "HM";  //Heard & McDonald Is 
        public static string Honduras => "HN";  //Honduras 
        public static string HongKong => "HK";  //Hong Kong 
        public static string Hungary => "HU";  //Hungary 
        public static string Iceland => "IS";  //Iceland 
        public static string India => "IN";  //India 
        public static string Indonesia => "ID";  //Indonesia 
        public static string IranIslamicRepl => "IR";  //Iran (Islamic Repl) 
        public static string Iraq => "IQ";  //Iraq 
        public static string Ireland => "IE";  //Ireland 
        public static string IsleOfMan => "IM";  //Isle of Man 
        public static string Israel => "IL";  //Israel 
        public static string Italy => "IT";  //Italy 
        public static string Jamaica => "JM";  //Jamaica 
        public static string Japan => "JP";  //Japan 
        public static string JerseyCI => "JE";  //Jersey C.I. 
        public static string Jordan => "JO";  //Jordan 
        public static string Kazakhstan => "KZ";  //Kazakhstan 
        public static string Kenya => "KE";  //Kenya 
        public static string Kiribati => "KI";  //Kiribati 
        public static string Korea => "KR";  //Korea 
        public static string KoreaDemPplRep => "KP";  //Korea, Dem Ppl Rep 
        public static string Kuwait => "KW";  //Kuwait 
        public static string Kyrgyzstan => "KG";  //Kyrgyzstan 
        public static string LaoPeopleDemRep => "LA";  //Lao People's Dem Rep 
        public static string Latvia => "LV";  //Latvia 
        public static string Lebanon => "LB";  //Lebanon 
        public static string Lesotho => "LS";  //Lesotho 
        public static string Liberia => "LR";  //Liberia 
        public static string LibyanArabJamah => "LY";  //Libyan Arab Jamah 
        public static string Liechtenstein => "LI";  //Liechtenstein 
        public static string Lithuania => "LT";  //Lithuania 
        public static string Luxembourg => "LU";  //Luxembourg 
        public static string Macau => "MO";  //Macau 
        public static string Madagascar => "MG";  //Madagascar 
        public static string Malawi => "MW";  //Malawi 
        public static string Malaysia => "MY";  //Malaysia 
        public static string Maldives => "MV";  //Maldives 
        public static string Mali => "ML";  //Mali 
        public static string Malta => "MT";  //Malta 
        public static string MarshallIslands => "MH";  //Marshall Islands 
        public static string Martinique => "MQ";  //Martinique 
        public static string Mauritania => "MR";  //Mauritania 
        public static string Mauritius => "MU";  //Mauritius 
        public static string Mexico => "MX";  //Mexico 
        public static string Micronesia => "FM";  //Micronesia 
        public static string MoldovaRepublicof => "MD";  //Moldova, Republic of 
        public static string Monaco => "MC";  //Monaco 
        public static string Mongolia => "MN";  //Mongolia 
        public static string Monserrat => "MS";  //Monserrat 
        public static string Morocco => "MA";  //Morocco 
        public static string Mozambique => "MZ";  //Mozambique 
        public static string Myanmar => "MM";  //Myanmar 
        public static string Namibia => "NA";  //Namibia 
        public static string Nauru => "NR";  //Nauru 
        public static string Nepal => "NP";  //Nepal 
        public static string NethAntilles => "AN";  //Neth Antilles 
        public static string Netherlands => "NL";  //Netherlands 
        public static string NeutralZone => "NT";  //Neutral Zone 
        public static string NewCaledonia => "NC";  //New Caledonia 
        public static string NewZealand => "NZ";  //New Zealand 
        public static string Nicaragua => "NI";  //Nicaragua 
        public static string Niger => "NE";  //Niger 
        public static string Nigeria => "NG";  //Nigeria 
        public static string Niue => "NU";  //Niue 
        public static string NorfolkIsland => "NF";  //Norfolk Island 
        public static string NorthernMarianaIs => "MP";  //Northern Mariana Is 
        public static string Norway => "NO";  //Norway 
        public static string Oman => "OM";  //Oman 
        public static string Pakistan => "PK";  //Pakistan 
        public static string Palau => "PW";  //Palau 
        public static string Palestine => "PS";  //PALESTINE 
        public static string Panama => "PA";  //Panama 
        public static string PanamaCanalZone => "PZ";  //Panama Canal Zone 
        public static string PapuaNewGuinea => "PG";  //Papua New Guinea 
        public static string Paraguay => "PY";  //Paraguay 
        public static string Peru => "PE";  //Peru 
        public static string Philippines => "PH";  //Philippines 
        public static string Pitcairn => "PN";  //Pitcairn 
        public static string Poland => "PL";  //Poland 
        public static string Portugal => "PT";  //Portugal 
        public static string PuertoRico => "PR";  //Puerto Rico 
        public static string Qatar => "QA";  //Qatar 
        public static string Reunion => "RE";  //Reunion 
        public static string Romania => "RO";  //Romania 
        public static string RussianFederation => "RU";  //Russian Federation 
        public static string Rwanda => "RW";  //Rwanda 
        public static string SaintLucia => "LC";  //Saint Lucia 
        public static string Samoa => "WS";  //Samoa 
        public static string SanMarino => "SM";  //San Marino 
        public static string SaoTomeAndPrincipe => "ST";  //Sao Tome & Principe 
        public static string SaudiArabia => "SA";  //Saudi Arabia 
        public static string Senegal => "SN";  //Senegal 
        public static string Seychelles => "SC";  //Seychelles 
        public static string SierraLeone => "SL";  //Sierra Leone 
        public static string Singapore => "SG";  //Singapore 
        public static string Slovakia => "SK";  //Slovakia 
        public static string Slovenia => "SI";  //Slovenia 
        public static string SolomonIslands => "SB";  //Solomon Islands 
        public static string Somalia => "SO";  //Somalia 
        public static string SouthAfrica => "ZA";  //South Africa 
        public static string Spain => "ES";  //Spain 
        public static string SriLanka => "LK";  //Sri Lanka 
        public static string StHelena => "SH";  //St Helena 
        public static string StKittsAndNevis => "KN";  //St Kitts and Nevis 
        public static string StPierreAndMiquelon => "PM";  //St Pierre & Miquelon 
        public static string StVincentAndTheGre => "VC";  //St Vincent & the Gre 
        public static string StatelessBedoun => "S9";  //Stateless (Bedoun) 
        public static string Sudan => "SD";  //Sudan 
        public static string Suriname => "SR";  //Suriname 
        public static string SvalbardAndJanMayan => "SJ";  //Svalbard & Jan Mayan 
        public static string Swaziland => "SZ";  //Swaziland 
        public static string Sweden => "SE";  //Sweden 
        public static string Switzerland => "CH";  //Switzerland 
        public static string SyrianArabRepublic => "SY";  //Syrian Arab Republic 
        public static string Taiwan => "TW";  //Taiwan 
        public static string Tajikistan => "TJ";  //Tajikistan 
        public static string TanzaniaUtdRepOf => "TZ";  //Tanzania, Utd Rep of 
        public static string Thailand => "TH";  //Thailand 
        public static string Togo => "TG";  //Togo 
        public static string Tokelau => "TK";  //Tokelau 
        public static string Tonga => "TO";  //Tonga 
        public static string TrinidadAndTobago => "TT";  //Trinidad & Tobago 
        public static string Tunisia => "TN";  //Tunisia 
        public static string TurkaAndCaicosIs => "TC";  //Turka & Caicos Is 
        public static string Turkey => "TR";  //Turkey 
        public static string Turkmenistan => "TM";  //Turkmenistan 
        public static string Tuvalu => "TV";  //Tuvalu 
        public static string Uganda => "UG";  //Uganda 
        public static string Ukraine => "UA";  //Ukraine 
        public static string UnitedArabEmirates => "AE";  //United Arab Emirates 
        public static string UnitedKingdom => "GB";  //United Kingdom 
        public static string UnitedStates => "US";  //United States 
        public static string Uruguay => "UY";  //Uruguay 
        public static string USMinorOutlayingI => "UM";  //US Minor Outlaying I 
        public static string Uzbekistan => "UZ";  //Uzbekistan 
        public static string Vanuatu => "VU";  //Vanuatu 
        public static string VaticanCityState => "VA";  //Vatican City State 
        public static string Venezuela => "VE";  //Venezuela 
        public static string Vietnam => "VN";  //Vietnam 
        public static string VirginIslandsBrit => "VG";  //Virgin Islands, Brit 
        public static string VirginIslandsUS => "VI";  //Virgin Islands, U.S. 
        public static string WallisAndFutunaIs => "WF";  //Wallis & Futuna Is 
        public static string WesternSahara => "EH";  //Western Sahara 
        public static string YemenRepublicOf => "YE";  //Yemen, Republic of 
        public static string Yugoslavia => "YU";  //Yugoslavia 
        public static string Zaire => "ZR";  //Zaire 
        public static string Zambia => "ZM";  //Zambia 
        public static string Zimbabwe => "ZW";  //Zimbabwe 

    }
}